### PR TITLE
support nested properties, simplify signature

### PR DESCRIPTION
**Pull request by jonschlinkert**
See [examples](https://github.com/jonschlinkert/group-array/tree/nesting#examples) and tests for details.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
btw this isn't a complete solution. I just wanted to talk through it to see if we can come up with a cross between this and the existing code. to simplify the API and still allow some of the power of passing custom functions (which isn't in this pr...)

**Comment by jonschlinkert** [comment]
ok, I updated it with basic support for functions.

allows stuff like:

``` js
var group = posts.groupBy('data.foo', function (obj) {
    return get(obj, 'data.year');
  }, function (obj) {
    return get(obj, 'data.month');
  }, function (obj) {
    return get(obj, 'data.day');
  })
```

**Comment by jonschlinkert** [comment]
I'm conflicted... I was thinking this might be better since it's simpler to create deeply nested groups, but the way you're doing it makes it easier to expose the list/collection methods (I think)... 

any thoughts?

**Comment by doowb** [comment]
After thinking about it more, I see how this can also be used with what I was thinking. It makes more sense to have this library be more opinionated instead of just making a glorified reduce function.

**Pull request merged**
